// Generated by gencpp from file cartesian_control/test_srv.msg
// DO NOT EDIT!


#ifndef CARTESIAN_CONTROL_MESSAGE_TEST_SRV_H
#define CARTESIAN_CONTROL_MESSAGE_TEST_SRV_H

#include <ros/service_traits.h>


#include <cartesian_control/test_srvRequest.h>
#include <cartesian_control/test_srvResponse.h>


namespace cartesian_control
{

struct test_srv
{

typedef test_srvRequest Request;
typedef test_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_srv
} // namespace cartesian_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartesian_control::test_srv > {
  static const char* value()
  {
    return "7a7ab05b8c54168563cc1cb286c04fa8";
  }

  static const char* value(const ::cartesian_control::test_srv&) { return value(); }
};

template<>
struct DataType< ::cartesian_control::test_srv > {
  static const char* value()
  {
    return "cartesian_control/test_srv";
  }

  static const char* value(const ::cartesian_control::test_srv&) { return value(); }
};


// service_traits::MD5Sum< ::cartesian_control::test_srvRequest> should match
// service_traits::MD5Sum< ::cartesian_control::test_srv >
template<>
struct MD5Sum< ::cartesian_control::test_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartesian_control::test_srv >::value();
  }
  static const char* value(const ::cartesian_control::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartesian_control::test_srvRequest> should match
// service_traits::DataType< ::cartesian_control::test_srv >
template<>
struct DataType< ::cartesian_control::test_srvRequest>
{
  static const char* value()
  {
    return DataType< ::cartesian_control::test_srv >::value();
  }
  static const char* value(const ::cartesian_control::test_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartesian_control::test_srvResponse> should match
// service_traits::MD5Sum< ::cartesian_control::test_srv >
template<>
struct MD5Sum< ::cartesian_control::test_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartesian_control::test_srv >::value();
  }
  static const char* value(const ::cartesian_control::test_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartesian_control::test_srvResponse> should match
// service_traits::DataType< ::cartesian_control::test_srv >
template<>
struct DataType< ::cartesian_control::test_srvResponse>
{
  static const char* value()
  {
    return DataType< ::cartesian_control::test_srv >::value();
  }
  static const char* value(const ::cartesian_control::test_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTESIAN_CONTROL_MESSAGE_TEST_SRV_H
